### ISSUE TITLE
Replace emojicodes with unicode emojis 

### ISSUE THREAD

**Issue by shalithasuranga** [shalithasuranga/emojicpp#5]
Some emoji codes not rendered on Github correctly. Replace with unicode version. This can be done by multiple contributors by replacing 10 by 10 emojis etc.

**Comment by suyasha0** [comment]
I can do the first 10 emojis that are rendered incorrectly.

**Comment by P1X3L0V4** [comment]
I can do second 10 emojis that are rendered incorrectly.

**Comment by SethJMoore** [comment]
I'll do the third 10 rendered incorrectly. Should the correctly rendered ones also be replaced in order to keep consistency through the file?

**Comment by aneeshnema** [comment]
I'll do the last 10

**Comment by shalithasuranga** [comment]
@SethJMoore good idea.. For now we just need to display those. So we can finalize this task first :)
